#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# packageVersion=$(node -p -e "require('./package.json').version")

packageVersion=$npm_package_version

echo "TEST = $packageVersion"

sed -i -e "s/CLIENT_VERSION = \".*\"/CLIENT_VERSION = \"$packageVersion\"/" ./src/lib/config/config.constants.ts
# -i = in-place edit
# Note there's no g flag used in the regular expression to make sure only one line is affected (just in case).

pnpm lint-staged

git update-index --again
